version: '3'
services: 
  app: 
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '4500:4500'
    volumes:
      - ./uploads:/src/public/uploads
    networks:
      - foodee-net
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - ./data/:/data/db
    networks:
      foodee-net:
volumes:
  mongodata:
    driver: local
networks:
  foodee-net:
