version: '3'
services: 
  app: 
    container_name: docker-node-mongo
    restart: always
    build: .
    ports:
      - '8080:4500'
      - '80:80'
      - '443:443'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - mongodata:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodata:
    driver: local